apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  ports:
  - name: 8761-tcp
    port: 8761
    protocol: TCP
    targetPort: 80
  selector:
    com.docker.project: eureka
  type: LoadBalancer
status:
  loadBalancer: {}
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.project: eureka
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: eureka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: eureka
    spec:
      containers:
      - image: rizkinu/discovery-service:1.4
        name: eureka
        ports:
        - containerPort: 8761
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}